Updating readme for typescript definitions and unit-testing
mozilla/webextension-polyfill pull request #330
Opened 2021-08-10 19:33 UTC by Lusito

- webextension-polyfill-ts is now [@types/webextension-polyfill](https://www.npmjs.com/package/@types/webextension-polyfill)
- Added a link to [mockzilla-webextension](https://lusito.github.io/mockzilla-webextension/), a unit-testing framework designed for web-extensions.

2021-08-19 13:34 UTC, rpl requested changes
@Lusito we just discussed about this PR in our triage meeting, we are ok to approve and merge the first commit (92c3734) which updated an npm package that the README is already mentioning, but not the second one about mockzilla-webextensions from this PR, which we suggest to reopen as a PR for a repo that is meant to be a directory of link to projects related to WebExtensions (e.g. https://github.com/fregante/Awesome-WebExtensions).

2021-08-22 12:00 UTC, Lusito commented
@rpl Thanks for the review. I've removed the second commit.

2021-08-23 11:13 UTC, Rob--W approved these changes

2021-08-23 12:23 UTC, rpl approved these changes

2021-08-23 12:23 UTC, merged

2021-08-31 20:33 UTC, caitmuenster commented
Thank you, @lusito! Hope you are doing well. :)