fix: Remove webpack and webpack-cli dependencies
mozilla/webextension-polyfill pull request #614
Opened 2024-05-14 14:01 UTC by Gudahtt

Changes made in #597 accidentally resulted in `webpack` and `webpack-cli` being added as dependencies in the manifest of the published package. This problem can be seen in v0.11.0. For more information, see #604.

`webpack` and `webpack-cli` are used for bundler smoke tests that are run in CI. Rather than being installed during CI, these dependencies are now included in `devDependencies`. A new npm script has been added for running this script as well, to ensure that these dependencies are on the PATH when this script is run.

The CircleCI config and the contributor docs have been updated to use the new npm script. You can test it by running
`npm run test-module-bundlers-smoketest`.

Fixes #604

2024-05-14 17:21 UTC, Rob--W commented on .circleci/config.yml
> -      - run: npm install browserify webpack webpack-cli
The fix for the bug is to add `--no-save` here, as mentioned at https://github.com/mozilla/webextension-polyfill/issues/604#issuecomment-2110749236

2024-05-14 17:34 UTC, Rob--W approved these changes

2024-05-14 17:35 UTC, merged

2024-05-14 17:36 UTC, Rob--W commented
Thanks for the analysis and fix. Although `--no-save` could have fixed the issue, adding it to devDependencies signals more clearly that it is a potential dependency in any test. It would also make it easier to identify external regressions in the smoke tests, hence I merged this PR instead of adding a `--no-save` fix.

2024-05-14 17:56 UTC, Gudahtt commented
Thanks! Good point that `--no-save` would have been simpler, I forgot that flag existed. I prefer this fix for the same reasons you mentioned though.

2025-06-28 05:33 UTC, yndaii requested changes

2025-06-28 05:33 UTC, yndaii commented on .circleci/config.yml
> -      - run: npm install browserify webpack webpack-cli
e2754582c72f99742aea07770b51c24ca3349f61